In [1]:
import pandas as pd

In [4]:
s1 = pd.Series([90,78,65,87,72])
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

In [5]:
data = [90,78,65,87,72]

In [6]:
s1 = pd.Series(data)

In [7]:
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

In [8]:
import numpy as np

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
s2 = pd.Series(np.arange(1,10,2))

In [11]:
s2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [12]:
data = np.arange(1,10,2)

In [13]:
s2 = pd.Series(data)
s2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [14]:
s1

0    90
1    78
2    65
3    87
4    72
dtype: int64

In [15]:
s1.dtypes

dtype('int64')

In [16]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
s1.index=['sato','suzuki','takahashi','tanaka','ito']
s1

sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
dtype: int64

In [19]:
s1.index

Index(['sato', 'suzuki', 'takahashi', 'tanaka', 'ito'], dtype='object')

In [20]:
dict01 = {'sato':90,'suzuki':78,'takahashi':65,'tanaka':87,'ito':72}

In [21]:
s3 = pd.Series(dict01)
s3

sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
dtype: int64

In [22]:
s1.values

array([90, 78, 65, 87, 72])

In [23]:
s1['suzuki']

78

In [24]:
s1[1]

78

In [26]:
s1[['suzuki','tanaka']]

suzuki    78
tanaka    87
dtype: int64

In [28]:
s1[[1,3]]

suzuki    78
tanaka    87
dtype: int64

In [29]:
s1 >80

sato          True
suzuki       False
takahashi    False
tanaka        True
ito          False
dtype: bool

In [30]:
s1[s1>80]

sato      90
tanaka    87
dtype: int64

In [31]:
s1[s1<=80]

suzuki       78
takahashi    65
ito          72
dtype: int64

In [32]:
s1.size

5

In [33]:
len(s1)

5

In [34]:
s1.index.name = 'member'
s1.name = 'score'
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [35]:
s1 + 2


member
sato         92
suzuki       80
takahashi    67
tanaka       89
ito          74
Name: score, dtype: int64

In [36]:
s1 - 2

member
sato         88
suzuki       76
takahashi    63
tanaka       85
ito          70
Name: score, dtype: int64

In [37]:
s1 *2

member
sato         180
suzuki       156
takahashi    130
tanaka       174
ito          144
Name: score, dtype: int64

In [38]:
s1 /2

member
sato         45.0
suzuki       39.0
takahashi    32.5
tanaka       43.5
ito          36.0
Name: score, dtype: float64

In [39]:
s2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [44]:
s2.index=['suzuki','takahashi','tanaka','ito','watanabe']

In [45]:
s2

suzuki       1
takahashi    3
tanaka       5
ito          7
watanabe     9
dtype: int64

In [46]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [47]:
s1 + s2

ito          79.0
sato          NaN
suzuki       79.0
takahashi    68.0
tanaka       92.0
watanabe      NaN
dtype: float64

In [48]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [49]:
s1.hasnans

False

In [52]:
s4 = pd.Series([90,78,65,None,72])
s4

0    90.0
1    78.0
2    65.0
3     NaN
4    72.0
dtype: float64

In [54]:
s4.hasnans

True

In [55]:
pd.isnull(s4)

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [56]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
                 columns=['col01','col02','col03'],
                 index=['idx01','idx02','idx03'])
df

col01  col02  col03
idx01      1      2      3
idx02      4      5      6
idx03      7      8      9

In [57]:
df['col01']

idx01    1
idx02    4
idx03    7
Name: col01, dtype: int64

In [58]:
type(df['col01'])

pandas.core.series.Series

In [59]:
s5 = pd.Series({'idx01':10,'idx02':11,'idx03':12})
s5

idx01    10
idx02    11
idx03    12
dtype: int64

In [60]:
df['col04']= s5
df

col01  col02  col03  col04
idx01      1      2      3     10
idx02      4      5      6     11
idx03      7      8      9     12

In [61]:
s6 =pd.Series({'idx03':13,'idx04':14,'idx05':15})
s6

idx03    13
idx04    14
idx05    15
dtype: int64

In [64]:
df['col05']= s6
df

col01  col02  col03  col04  col05
idx01      1      2      3     10    NaN
idx02      4      5      6     11    NaN
idx03      7      8      9     12   13.0

In [68]:
dates = pd.date_range('2000/01/01', periods = 5, freq = 'D')
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05'],
              dtype='datetime64[ns]', freq='D')

In [70]:
type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [71]:
s1

member
sato         90
suzuki       78
takahashi    65
tanaka       87
ito          72
Name: score, dtype: int64

In [72]:
s1.index=dates

In [73]:
s1

2000-01-01    90
2000-01-02    78
2000-01-03    65
2000-01-04    87
2000-01-05    72
Freq: D, Name: score, dtype: int64

In [74]:
name = ['sato','ito']
score = [90,80]
dict01 = {'ito':50,'suzuki':None}
df = pd.DataFrame([[90,75],[60,95]],
                  index=['sato','ito'],
                  columns=['English','Math'])
df

English  Math
sato       90    75
ito        60    95

In [76]:
s1 = pd.Series(score,name)
s1

sato    90
ito     80
dtype: int64

In [77]:
s_dict = pd.Series(dict01)
s_dict

ito       50.0
suzuki     NaN
dtype: float64

In [78]:
s1.index

Index(['sato', 'ito'], dtype='object')

In [79]:
s_dict.values

array([50., nan])

In [80]:
s1.values

array([90, 80])

In [81]:
s1 == 90

sato     True
ito     False
dtype: bool

In [82]:
s1[s1 == 90]

sato    90
dtype: int64

In [83]:
pd.isnull(s_dict)

ito       False
suzuki     True
dtype: bool

In [84]:
df['Science']= s1
df

English  Math  Science
sato       90    75       90
ito        60    95       80

In [85]:
df

English  Math  Science
sato       90    75       90
ito        60    95       80